CREATE DATABASE devworld;

USE devworld;

CREATE TABLE IF NOT EXISTS users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(256) NOT NULL,
  github_username VARCHAR(256) NOT NULL,
  email VARCHAR(128) NOT NULL,
  password VARCHAR(512) NOT NULL
);

CREATE TABLE IF NOT EXISTS favorited_users (
	id INT PRIMARY KEY AUTO_INCREMENT,
  github_username VARCHAR(256) NOT NULL,
  user_id INT NOT NULL,
  FOREIGN KEY(user_id) REFERENCES users(id)
);